swagger: "2.0"

info:
  title: "rpn api"
  version: "1.0"

basePath: /
paths:
  /rpm/op:
    get:
      operationId: api.core.rpn.list_all_operands
      summary: Get all operands
      responses:
        200:
          description: Successfully get all operands

  /rmp/op/{op}/stack/{stack_id}:
    post:
      operationId: api.core.rpn.apply_operand
      summary: Apply operand
      responses:
        201:
          description: Successfully apply
      parameters:
         - $ref: "#/parameters/stack_id"
         - $ref: "#/parameters/op"

  /rmp/stack:
    post:
      operationId: api.core.rpn.create_new_stack
      summary: Create new stack
      responses:
        201:
          description: Successfully create new stack
      parameters:
        - name: stack
          required: true
          in: body
          schema:
            $ref: "#/definitions/create_new_stack"
    get:
      operationId: api.core.rpn.get_all_stacks
      summary: List the available stacks
      responses:
        200:
          description: Successfully get all stack

  /rpm/stack/{stack_id}:
    delete:
      operationId: api.core.rpn.delete_stack
      summary: Delete a stack
      responses:
        200:
          description: stack deleted successfully
      parameters:
         - $ref: "#/parameters/stack_id"

    get:
      operationId: api.core.rpn.get_stack
      summary: Get a stack
      responses:
        200:
          description: get stack successfully
      parameters:
         - $ref: "#/parameters/stack_id"

    post:
      operationId: api.core.rpn.push_value_stack
      summary: Push a new value to a stack
      responses:
        201:
          description: Successfully push value
      parameters:
        - $ref: "#/parameters/stack_id"
        - name: value
          required: true
          in: query
          type: integer

definitions:
 create_new_stack:
  type: array
  items:
    type: integer
  example: [1, 2]

parameters:
  stack_id:
    in: path
    name: stack_id
    required: true
    type: string
  op:
    in: path
    name: op
    required: true
    type: string
    enum: [mul, add, div , sub]
    default: add